# Generated by Django 5.0.2 on 2024-09-11 13:52

import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_event_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendance_date",
            field=models.DateTimeField(auto_now_add=True, default=now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
