# Generated by Django 5.0.2 on 2024-03-01 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="event",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainapp.event",
            ),
        ),
    ]
